[build-system]
requires = ["flit_core >=3,<4"]
build-backend = "flit_core.buildapi"


[tool.flit.metadata]
module = "AllocCant"
author = "Trent W. Buck"
requires = [
    "requests",
    "pypass",
    ]

[tool.flit.scripts]
"alloc-cant" = "AllocCant:main"
